# Generated by Django 3.1.7 on 2021-03-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=156)),
                ('chapter_no', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Civics Question',
                'verbose_name_plural': 'Civics Questions',
            },
        ),
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=156)),
                ('chapter_no', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Economics Question',
                'verbose_name_plural': 'Economics Questions',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=156)),
                ('chapter_no', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Geography Question',
                'verbose_name_plural': 'Geography Questions',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=156)),
                ('chapter_no', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'History Question',
                'verbose_name_plural': 'History Questions',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=156)),
                ('chapter_no', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Science Question',
                'verbose_name_plural': 'Science Questions',
            },
        ),
    ]
