# Generated by Django 3.1.7 on 2021-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210325_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maths',
            name='answer',
            field=models.TextField(),
        ),
    ]
